# Generated by Django 3.1.5 on 2021-01-21 00:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Ingrese su email.', max_length=254)),
                ('name', models.CharField(help_text='Ingrese su nombre o apodo.', max_length=20)),
                ('phone', models.CharField(help_text='Ingrese su numero con +569...', max_length=12)),
                ('message', models.CharField(help_text='Ingrese algun mensaje para nosotros.', max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
